apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voice-api
  template:
    metadata:
      labels:
        app: voice-api
    spec:
      containers:
        - name: voice-api
          image: voice-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: voice-api-service
spec:
  type: NodePort # ローカルからアクセスしやすくするための設定
  selector:
    app: voice-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
